### ISSUE TITLE
Avoid user confusion over custom project names

### ISSUE THREAD

**Issue by bmozaffa** [RHsyseng/IntegrationApp-Automation#4]
Project names currently need to be specified/changed in the env.sh file, as well as passed as template parameters for each pipeline.

Let's either include the 5 pipeline setups in the setup.sh script, in which case we could then pass the project names to them as variables from env.sh. If so, we should then also remove the default template parameters, so anyone running the template directly is forced to provide it through a flag.

If the above is not an option, for whatever reason, it might be best to not provide a clean and separate env.sh file, which I think provides an illusion to the user that they can modify project names from a central location.

**Comment by myeung18** [comment]
I think for a better user experience, they don't need to change any file before start our application, if customization is needed, pass in as parameters.

 If we put the pipelines into the setup scripts, we can change the existing script a bit so that user can pass in those three project names as parameters and this similar issue could be avoided. However, how about the other parameters? There are quite a few and should we allow user to pass in to the script as well?  I separated the pipelines out was cos I don't want to add too many checks and logics in the script (make it simple).

I think remove those default values from the templates could be a way to go. that means we force user to provide them before creating the pipelines.
Or we can still include those pipelines in the shell script, and only let user to customize the project names.  If they want to customize other parameters, they delete the pre-created pipelines and create their customized pipelines by providing all the mandatory parameters.

**Comment by bmozaffa** [comment]
My point is that env.sh provides the illusion of easily changing project names. That's the biggest issue right now.

I don't think we need to make everything easily configurable. If the default values are removed for project names only, from the template, and the template is called from the script, we can have your desired effect of simple call to setup.sh with no parameters to build a default, but also one central place to change project names in env.sh. It's ok for it to be harder to change some of the other configuration.

**Comment by myeung18** [comment]
I see, I am ok with this.
